
# Dockerfile.dev
FROM node:18

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Install netcat for wait-for-db.sh (if used)
RUN apt-get update && apt-get install -y netcat-openbsd


# Install dev dependencies like nodemon globally if needed
RUN npm install -g nodemon

# Expose the application port
EXPOSE 3000

# Command to run the application
CMD ["npm", "run","start:dev"] 