name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # or your specific version

      - name: Install Dependencies
        run: npm install

      # - name: Run Tests
      #   run: npm run test

      # - name: Build Application
      #   run: npm run build

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          EC2_IP: ${{ secrets.EC2_PUBLIC_IP }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@$EC2_IP << 'EOF'
            cd /home/ubuntu/fusionlink
            git reset --hard
            git pull origin main
            npm install --legacy-peer-deps
            npm run build
            pm2 reload fusionlink || pm2 start ecosystem.config.js --only fusionlink
          EOF
