name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # or your specific version

      - name: Install Dependencies
        run: npm install

      # - name: Run Tests
      #   run: npm run test

      # - name: Build Application
      #   run: npm run build
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          EC2_IP: ${{ secrets.EC2_PUBLIC_IP }}
        run: |
          echo -----BEGIN CERTIFICATE-----
              LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVB
              MmJuQlNmVmdaZ2FJcitMa1FGUndISFFldm1nNFB3emp2NnJUVFh5T3YzRzBoRXlC
              CldNYnZkVENuOVY1TjBUM1J0NmlGbWhCWWthV1RyUHplYlBOZkJITTBiWG5CRS9l
              ZDRyem9jMlZPeVR4UkIvMWEKU2VrTUNoMlVsVitlUlU5WE1YaHJGajFTeS9UTEQz
              RXgyVHQrODAwbXBTZHovaERaTkZEWHJMbUp2QUZqZU9DbApWbEV0am1uc0dmZmND
              OWlzajBZbkNndkhTY0M5bjlZazl3VnBzV0xGbjNBblZRcENmNEF3aVBqeEdLeXB2
              YmcxClUwWm1EeUR3T2ZJclVqK0FnMFE0M2l4a2JqUXh1b29xRDVjNHhWWkJIb1BI
              TmNwUkxoVXk1amU5dmlWV0lIQkwKcFVhZ0hrM3poUUE3b25OQVR1ZC9uWjUzbDM5
              Mnh2ZkpxdWlyb1FJREFRQUJBb0lCQUNnYTkyZlFNem1YNm9XNwpuWi9iN2VyUDJQ
              bnA2TEowaFY5QThEdE52bDIxYkRNU2hLRDl4QTRxTUVZYVlPc3lIL2RjcTM5OWsx
              TUExUHNBCmVWaElYREJOcUZLaUl0YXl2ZnFPSWFOZi9ldERtUW1IdWFIenM2d0pW
              dDFOQjdKc3N2c0IyM2YxUTlNZC9HbVQKeUVMam1yYm1kei9rekpENE9ZcFJlZWp2
              SkZmazhwdHpyZmgvM3hXWjhZUzhNTVJUOXdxSkFncGs4bmt6VmdVQQpCQVoyczdY
              cXV1eVBzTnhabCt5cVVDVmdHVGV0K2FzZ3ZNZXhhaHU1dmtWYk9WQjRhbzViQ0tE
              MjBlUzRlWHVhCjZyVDgxbVZ6TnFrUVJrQml4Z3lZMC9IUloybmRNRW9ncytCbnYz
              U3E0R2xsTXJiTE5NYmY4Qzdpa0hrNXQ3M3MKYnhKaXZ5RUNnWUVBN1RJSVBIcjZZ
              ZTVyZldOVC9GbTBMRDZ1Y0JPT2xaeUJyM2lEWXdIWUs4UGpUbG0zSG9HNQpMNHpK
              cVRvaGs5c0d3UHBNdEVyalVSQ2VxVmdBRUpKMDI5V3RVUFd2SHRIV0wyUUdReHFH
              MVBGVEtNVVhRS3N3ClgxUW9leXVyYWVvNWgyRHBQc3htdEhKc3AvSlkzRUN0OWZv
              Sk9zUVRqYVpUSnpqOHJjbG8wQ3NDZ1lFQTZ2eVQKVlJiRENrZHFXUWJEVDlLZFk2
              ME0yRSsrNmgvT1FXRmlnMk82Mmo3Mlh6Si9QU2xHemZBZTdoOHFMc01DVnRlTwpu
              NDkzTzJVNy8vME96YVo2S21NcUxyeVAzMmc4SGhMbTE5eE9FZ0pLeFBZSVJ4UXFM
              ZXVYaXVLa09Nakwzak5nCmFaOGVBOVpwbGNuWElGdUpxdnk0ZFE0VFV6YXV3QW9U
              UTBPd0FXTUNnWUJyN3Y1c2R4R0VpcmVEQVRYd2VPbFIKME53VHgvSjBCaG5GUFRP
              Y1UvU0lSY1VqbkJPRjRFWGlhMUJBbjJFMEpOQzM4NjMveEt3WDhWWWhmUmZhY3Fx
              VwpkbTg5amU2NE9ZZ2JYSXEwOGxjMGd2UHljMjBYVWs3YXNqTVJpVmVoQktKVkJq
              WmRDeW9aSnBCbkJCS0hkeTh4CjVTdGFBR3RkWTdnbSt2bVFJeng4clFLQmdCeEpW
              UzdyODRSOFBrZ0RNV1dkYzhhNDRRLzA0WVZyV0xlMEVsakEKbTVDRC9jSk40TlVx
              NzlRQWNLaTNaYXVGVy9XNk12ZndIQ2t4TVh6S0tJc0czRFBZQmc3a01lbHhzYkxw
              RVpLdwplVkZmcDBKNFgxeTNCN0RKYUUrV29yQVhNN3RHc2ZkazZRY0xPMkNGa0hq
              YnJBSENOQzRiQ0taK3NhQjZWZ0ZGCjE1MERBb0dBVzVCK204RXR4UWE5S2xUWGp4
              M0VYZnpjclFBRTFDUFlyUmgyZnpQWi9CZHVXQi9VUkxyVVVhQTAKT1Z2MkFud0tK
              L1VHWjQ4ZjBqTDJ5UWdvTnJZQmNSRGtXb0prMW5EUFJJNGRMRjMzY2pzYVlkNEFv
              U0pHRVFUNQovUmlkZi9HTVhYMGdZakZUV0xYOEVRQnhaejVyK1hCRm5jQjlWUngy
              RFVYaGtSUHZhSk09Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t
              -----END CERTIFICATE-----

          chmod 600 private_key.pem
      
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@16.171.234.167 
            cd /home/ubuntu/fusionlink
            git reset --hard
            git pull origin main
            npm install --legacy-peer-deps
            npm run build
            pm2 reload fusionlink || pm2 start ecosystem.config.js --only fusionlink
          EOF
      
